apiVersion: apps/v1
kind: Deployment
metadata:
  name: adm-server
  namespace: adm-2
  labels:
    app: adm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adm-server
  template:
    metadata:
      labels:
        app: adm-server
    spec:
      containers:
        - name: adm-server
          image: docker.pkg.github.com/didream/adm-visualizacion-datos-ii/adm-server-2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: dockerconfigjson-github-com