apiVersion: v1
kind: Service
metadata:
  name: adm-server
  namespace: adm-2
  labels:
    app: adm-server
spec:
  type: ClusterIP
  selector:
    app: adm-server
  ports:
    - protocol: TCP
      port: 3000 # Puerto del servicio
      targetPort: 3000 # Puerto del contenedor