apiVersion: apps/v1
kind: Deployment
metadata:
  name: adm-client
  namespace: adm-2
  labels:
    app: adm-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adm-client
  template:
    metadata:
      labels:
        app: adm-client
    spec:
      containers:
        - name: adm-client
          image: docker.pkg.github.com/didream/adm-visualizacion-datos-ii/adm-client:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerconfigjson-github-com