name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

jobs:
  server_to_registry:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: server/etc/Dockerfile
          path: .
          repository: didream/adm-visualizacion-datos-i/adm-server
          tag_with_sha: true
          tag_with_ref: true
          tags: ${{ github.sha }}

  deploy_to_gke:
    name: Deploy image version to GKE
    runs-on: ubuntu-latest
    env:
      # Datos GKE
      PROJECT_ID: ${{ secrets.GKE_PROJECT }}
      GKE_CLUSTER: cluster-1
      GKE_ZONE: europe-north1-a

      # Datos del despliegue en k8s
      NAMESPACE_NAME: adm
      DEPLOYMENT_NAME: adm-server-1-deployment
      CONTAINER_NAME: adm-server-1
      IMAGE_NAME: docker.pkg.github.com/didream/adm-visualizacion-datos-i/adm-server

    steps:
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Get the GKE credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

      - name: Update container image
        run: |-
          kubectl set image deployment/"$DEPLOYMENT_NAME" "$CONTAINER_NAME"="$IMAGE_NAME":"${{ github.sha }}" -n "$NAMESPACE_NAME"